name: ci

on:
  push:
    tags:
      - '*'
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Get dependencies
        run: go mod download

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=5m

  build:
    name: Build
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Get dependencies
      run: go mod download

    - name: Build Linux amd64
      run: env GOOS=linux GOARCH=amd64 go build -o degit_linux-amd64 ./cmd/degit.go

    - name: Build Windows amd64
      run: env GOOS=windows GOARCH=amd64 go build -o degit_windows-amd64.exe ./cmd/degit.go

    - name: Build macOS arm64
      run: env GOOS=darwin GOARCH=arm64 go build -o degit_darwin-amd64 ./cmd/degit.go

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: degit_*
        retention-days: 1

  release:
    name: Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: binaries

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: degit_*
