name: Go

on:
  push:
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Print directory structure
      run: ls -R

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'

    - name: Get dependencies
      run: go mod download

    - name: Build Linux amd64
      run: env GOOS=linux GOARCH=amd64 go build -o degit_linux-amd64

    - name: Build Windows amd64
      run: env GOOS=windows GOARCH=amd64 go build -o degit_windows-amd64.exe

    - name: Build macOS arm64
      run: env GOOS=darwin GOARCH=arm64 go build -o degit_darwin-amd64

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        path: degit_*

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: degit_*
