# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'

    - name: Build Linux amd64
      run: env GOOS=linux GOARCH=amd64 go build -o degit_linux-amd64 -v ./...

    - name: Build Windows amd64
      run: env GOOS=windows GOARCH=amd64 go build -o degit_windows-amd64 -v ./...

    - name: Build macOS arm64
      run: env GOOS=darwin GOARCH=arm64 go build -o degit_darwin-amd64 -v ./...

    - name: Upload artifacts
      uses: actions/upload-artifact@v4.3.0
      with:
        path: degit_*
